### ISSUE TITLE
Criar versão internacional da documentação

### ISSUE THREAD

**Issue by AlbericoD** [AlbericoD/OBS-widgets#11]
como todos sabem, a twitch não possui apenas brasileiros, precisamos transformar nossa documentação principal em inglês e as ramificações para os idiomas desejados, isso vai aumentar a visibilidade do nosso projeto

acho que seria algo assim:

README.md = em inglês
README-pt-br.md = em português

**Comment by a-ciacaicedo** [comment]
Hi, could I translate your README file for you? 
While I'm not fluent in Portuguese, I am fluent in English and Spanish. I know it isn't perfect, but for the most part I understand what the documentation says and I would love to help.

**Comment by AlbericoD** [comment]
hi @agarcia-caicedo , it would be amazing if you do that! xD
