### ISSUE TITLE
Traduzir código de conduta

### ISSUE THREAD

**Issue by AlbericoD** [AlbericoD/OBS-widgets#14]
Foi criado um código de conduta com o template padrão do github, porém ele não está traduzido para pt-br, (CODE_OF_CONDUCT.md)

o arquivo traduzido seria: CODE_OF_CONDUCT-pt-br.md

**Comment by karenngomes** [comment]
Irei fazer! :)

**Comment by cailir** [comment]
O [código de conduta](https://github.com/AlbericoD/live-stream-tools/blob/master/CODE_OF_CONDUCT_Pt-Br.md) já está pronto. [https://github.com/AlbericoD/live-stream-tools/blob/master/CODE_OF_CONDUCT_Pt-Br.md](https://github.com/AlbericoD/live-stream-tools/blob/master/CODE_OF_CONDUCT_Pt-Br.md)

**Comment by AlbericoD** [comment]
muito obrigado por avisar @cailir, irei fechar essa issue
