### ISSUE TITLE
Mensagem vindo duplicadas do chat da twitch

### ISSUE THREAD

**Issue by AlbericoD** [AlbericoD/OBS-widgets#4]
quando recarregamos algum modulo do frontend com o backend já em execução, as mensagens do backend começam a ficar duplicadas

**Comment by cailir** [comment]
Será corrigido caso a pull request [#26](https://github.com/AlbericoD/live-stream-tools/pull/26) seja aceita.

**Comment by AlbericoD** [comment]
acabei de fazer o merge, obrigado pelo aviso
